version: "3"
services:
  web:
    build: .
    ports:
      - "8050:8050"
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      DATABASE_PARAMS: Driver={ODBC Driver 17 for SQL Server};Server=tcp:db,1433;Database=sqldb-web-prod-001;Uid=sa;Pwd=Cl1mat3m1nd!;Encrypt=no;TrustServerCertificate=no;Connection Timeout=30;
      FLASK_APP: "climatemind.py"
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    command: bash -c " /db-init.sh & /opt/mssql/bin/sqlservr"
    environment:
      SA_PASSWORD: "Cl1mat3m1nd!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./entrypoint_db.sh:/entrypoint_db.sh
      - ./db-init.sh:/db-init.sh